server:
  port: 8030

token: b3b153dae2f9070edf185c150075cf18

auth:
  audience: currency-service

spring:
  application:
    name: currency-service
  security:
    email: aleksejivanniko@yandex.ru
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://dev-z6wzbvpa.us.auth0.com/

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:9999/eureka}
