version: '3'

services:
  discovery:
    build:
      context: ../Final Project/discovery-service
      dockerfile: Dockerfile
    image: discovery-image
    environment:
      - EUREKA_URL=http://discovery:9999/eureka
    ports:
      - 9999:9999
    container_name: discovery-container
    networks:
      - account-network

  gateway:
    build:
      context: ../Final Project/gateway-service
      dockerfile: Dockerfile
    image: gateway-image
    environment:
      - EUREKA_URL=http://discovery:9999/eureka
    ports:
      - 8888:8888
    container_name: gateway-container
    depends_on:
      - discovery
    networks:
      - account-network

  account:
    build:
      args:
        - JAR_FILE=target/*.jar
      context: ../Final Project/account-service
      dockerfile: Dockerfile
    image: stock-image
    environment:
      - EUREKA_URL=http://discovery:9999/eureka
    container_name: account-container
    depends_on:
      - discovery
    networks:
      - account-network

  currency:
    build:
      args:
        - JAR_FILE=target/*.jar
      context: ../Final Project/currency-service
      dockerfile: Dockerfile
    image: stock-image
    environment:
      - EUREKA_URL=http://discovery:9999/eureka
    container_name: currency-container
    depends_on:
      - discovery
    networks:
      - account-network

  stock:
    build:
      args:
        - JAR_FILE=target/*.jar
      context: ../Final Project/stock-service
      dockerfile: Dockerfile
    image: stock-image
    environment:
      - EUREKA_URL=http://discovery:9999/eureka
    container_name: stock-container
    depends_on:
      - discovery
    networks:
      - account-network

  networks:
    account-network: