server:
  port: 8000

auth:
  audience: account-service

convert-url: http://localhost:8010/account-amount-to-rub

spring:
  application:
    name: account-service
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://dev-z6wzbvpa.us.auth0.com/
  datasource:
    url: jdbc:postgresql://localhost:5432/account
    username: postgres
    password: 123
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: validate

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:9999/eureka}
