server:
  port: 8010

url: http://data.fixer.io/api/latest?access_key=%s&base=EUR&symbols=%s

token: 91f1498e8b2e0594c1482b7165af38d7

auth:
  audience: currency-service

spring:
  application:
    name: currency-service
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://dev-z6wzbvpa.us.auth0.com/
  autoconfigure:
    exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:9999/eureka}